const movies=[
{id:1,title:'Inception',year:2010,genre:['Ciencia ficción','Acción'],rating:8.8,description:'Un ladrón especializado en extraer secretos mediante sueños recibe una misión que consiste en implantar una idea en la mente de otra persona.',poster:'img/inception.jpg'},
{id:2,title:'Interstellar',year:2014,genre:['Ciencia ficción','Drama'],rating:8.7,description:'Un grupo de exploradores viaja a través de un agujero de gusano para buscar un nuevo hogar para la humanidad.',poster:'img/interestelar.jpg'},
{id:3,title:'The Batman',year:2022,genre:['Crimen','Drama'],rating:7.7,description:'Batman investiga una serie de crímenes mientras descubre una red de corrupción relacionada con el pasado de Ciudad Gótica.',poster:'img/batman.jpg'},
{id:4,title:'The Dark Knight',year:2008,genre:['Acción','Drama'],rating:9.0,description:'Batman se enfrenta a un criminal que busca sumir a Ciudad Gótica en el caos y poner a prueba los límites del héroe.',poster:'img/thedarkknight.jpg'},
{id:5,title:'Spider-Man: Into the Spider-Verse',year:2018,genre:['Animación','Acción'],rating:8.4,description:'Miles Morales descubre que no es el único Spider-Man y aprende a asumir su papel como héroe.',poster:'img/spiderman.jpg'},
{id:6,title:'Dune: Part Two',year:2024,genre:['Ciencia ficción','Aventura'],rating:8.6,description:'Paul Atreides se une a Chani y los Fremen mientras busca venganza y se prepara para un conflicto que puede cambiar el destino del universo.',poster:'img/dune.jpg'}
];
function getList(){return JSON.parse(localStorage.getItem('cinematch-list')||'[]')}
function saveList(list){localStorage.setItem('cinematch-list',JSON.stringify(list));updateBadge()}
function updateBadge(){document.querySelectorAll('#countBadge').forEach(e=>e.textContent=getList().length)}
function card(m){const list=getList();const saved=list.includes(m.id);return `<div class="col-12 col-sm-6 col-lg-4"><article class="movie-card"><img class="poster" src="${m.poster}" alt="Portada de ${m.title}"><div class="movie-body"><div class="d-flex justify-content-between gap-2"><h3 class="h5 fw-bold mb-1">${m.title}</h3><span class="rating">★ ${m.rating}</span></div><p class="text-secondary mb-2">${m.year} · ${m.genre[0]}</p><p class="small text-secondary">${m.description}</p><div class="d-flex gap-2"><a class="btn btn-sm btn-outline-light flex-grow-1" href="pelicula.html?id=${m.id}">Ver detalles</a><button class="btn btn-sm ${saved?'btn-danger':'btn-outline-danger'} save-btn" data-id="${m.id}">${saved?'♥':'♡'}</button></div></div></article></div>`}
function renderHome(){const grid=document.querySelector('#movieGrid');if(!grid)return;renderMovies(movies);document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#searchInput').value.toLowerCase().trim();const found=movies.filter(m=>m.title.toLowerCase().includes(q)||m.genre.join(' ').toLowerCase().includes(q));renderMovies(found);document.querySelector('#resultText').textContent=q?`${found.length} resultado(s) para “${q}”.`:'Explora algunas opciones para empezar.'})}
function renderMovies(arr){const grid=document.querySelector('#movieGrid');grid.innerHTML=arr.length?arr.map(card).join(''):`<div class="col-12"><div class="empty">No encontramos películas con esa búsqueda.</div></div>`;bindSave()}
function bindSave(){document.querySelectorAll('.save-btn').forEach(btn=>btn.addEventListener('click',()=>{const id=Number(btn.dataset.id);const list=getList();const next=list.includes(id)?list.filter(x=>x!==id):[...list,id];saveList(next);btn.innerHTML=next.includes(id)?'♥':'♡';btn.classList.toggle('btn-danger',next.includes(id));btn.classList.toggle('btn-outline-danger',!next.includes(id));showToast(next.includes(id)?'Película agregada a Mi lista':'Película eliminada de Mi lista')}))}
function renderDetail(){const box=document.querySelector('#movieDetail');if(!box)return;const id=Number(new URLSearchParams(location.search).get('id'))||1;const m=movies.find(x=>x.id===id)||movies[0];const saved=getList().includes(m.id);box.innerHTML=`<div class="col-lg-5"><img class="detail-poster" src="${m.poster}" alt="Portada de ${m.title}"></div><div class="col-lg-7"><p class="text-danger fw-bold">DETALLES DE LA PELÍCULA</p><h1 class="display-4 fw-bold">${m.title}</h1><p class="lead text-secondary">${m.year} · ${m.genre.join(' · ')} · <span class="rating">★ ${m.rating}</span></p><div class="mb-3">${m.genre.map(g=>`<span class="pill">${g}</span>`).join('')}</div><p class="fs-5 text-secondary">${m.description}</p><button id="detailSave" class="btn ${saved?'btn-danger':'btn-outline-danger'} btn-lg">${saved?'♥ En mi lista':'♡ Agregar a mi lista'}</button><a href="index.html" class="btn btn-outline-light btn-lg ms-2">Volver</a></div>`;document.querySelector('#detailSave').addEventListener('click',()=>{const list=getList();const next=list.includes(m.id)?list.filter(x=>x!==m.id):[...list,m.id];saveList(next);renderDetail();showToast(next.includes(m.id)?'Película agregada a Mi lista':'Película eliminada de Mi lista')})}
function renderList(){const grid=document.querySelector('#listGrid');if(!grid)return;const list=getList();const savedMovies=movies.filter(m=>list.includes(m.id));grid.innerHTML=savedMovies.length?savedMovies.map(card).join(''):`<div class="col-12"><div class="empty"><div class="fs-1 mb-2">🎞️</div><h2 class="h4">Tu lista está vacía</h2><p>Agrega películas desde Inicio o desde su página de detalles.</p><a class="btn btn-danger" href="index.html">Explorar películas</a></div></div>`;bindSave()}
function showToast(text){const el=document.createElement('div');el.className='toast-msg alert alert-dark border-secondary shadow';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
document.addEventListener('DOMContentLoaded',()=>{updateBadge();renderHome();renderDetail();renderList()});
